name: Run Autospin

on:
  schedule:
    - cron: '5/5 * * * *'  # every 5 minutes (UTC)
  workflow_dispatch:       # still allows manual trigger from GitHub UI
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - 'auto-spin/config.yaml'
  push:
    branches:
      - 'main'
    paths:
      - 'auto-spin/config.yaml'

concurrency:
  group: "autosping"
  cancel-in-progress: false


jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # or whichever version you prefer

    - name: Install dependencies
      run: |
        cd auto-spin
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python script
      env:
        F7T_CLIENT_ID: ${{ secrets.F7T_CLIENT_ID }}
        F7T_CLIENT_SECRET: ${{ secrets.F7T_CLIENT_SECRET }}
      run: |
        cd auto-spin/src
        python -m autospin.spawn-model ../config.yaml